name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  flutter_spinkit: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: SpartanMB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
  assets:
    - images/
